[phases.setup]
packages = [ "python3", "gcc" ]

[phases.build]
commands = [
  "pip install -r requirements.txt",
  "cd chatapp",  # Then go to subfolder with manage.py
  "python manage.py migrate"
]

[phases.start]
cmd = "cd django/chatapp && daphne chatapp.asgi:application"
